= lsh_01

lsh_01 logstash-http-input to syslog bridge

== Features

Listens to HTTP requests and sends them forward using RELP

== Documentation

Example configuration can be found link:etc/config.properties[here]

Currently supported configurations:

[%header,format=csv]
|===
Key,Default Value,Notes
server.listenAddress,127.0.0.1,Address the server will listen to
server.listenPort,8080,Port the server will listen to
server.threads,1,How many threads the server will use
server.maxPendingRequests,128,How many pending requests are allowed
server.maxContentLength,262144,How big requests are allowed in bytes
relp.target,127.0.0.1,RELP server address
relp.port,601,RELP server port
relp.reconnectInterval,10000,How long to wait before reconnecting in milliseconds
relp.appName,lsh_01,Appname to use in RELP records
relp.hostname,localhost,Hostname to use in RELP records
security.tokenRequired,true,Sets whether "Authorization: SomeSecretToken" headers are required
security.token,SomeSecretToken,A token every request must contain if security.tokenRequired is enabled.
|===

== Limitations

Developed on and requires java 11

Doesn't support SSL

== How to [compile/use/implement]

Run maven on java 11

`mvn clean package`

== How to run in a container

Mount configurations to `/config/` and run.

Expected files are `/config/config.properties` and `/config/log4j2.xml`

For example

`docker run -ti -v /path/to/config:/config ghcr.io/teragrep/lsh_01:latest`

== Contributing

You can involve yourself with our project by https://github.com/teragrep/lsh_01/issues/new/choose[opening an issue] or submitting a pull request.

Contribution requirements:

. *All changes must be accompanied by a new or changed test.* If you think testing is not required in your pull request, include a sufficient explanation as why you think so.
. Security checks must pass
. Pull requests must align with the principles and http://www.extremeprogramming.org/values.html[values] of extreme programming.
. Pull requests must follow the principles of Object Thinking and Elegant Objects (EO).

Read more in our https://github.com/teragrep/teragrep/blob/main/contributing.adoc[Contributing Guideline].

=== Contributor License Agreement

Contributors must sign https://github.com/teragrep/teragrep/blob/main/cla.adoc[Teragrep Contributor License Agreement] before a pull request is accepted to organization's repositories.

You need to submit the CLA only once. After submitting the CLA you can contribute to all Teragrep's repositories.
